name: pdr
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - cytoolz
  - numpy
  - pandas>=2.0.0
  - git
  - dustgoggles
  - pip
  - python-Levenshtein
  - multidict
  - more-itertools
  # optional dependencies (use minimal_environment.yml if you'd prefer not to install)
  - pvl
  - astropy
  - jupyter
  - pillow
  - matplotlib
  - pytest
