name: pdr
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - cytoolz
  - numpy
  - pandas>=2.0.0
  - git
  - dustgoggles
  - pip
  - multidict
  - more-itertools
  - rms-vax
  # optional dependencies (use minimal_environment.yml if you'd prefer not to install)
  - pvl
  - astropy
  - jupyter
  - pillow
  - pytest
  - Levenshtein
