site_name: Planetary Data Reader
site_description: one tool to read them all; https://github.com/MillionConcepts/pdr
theme:
  name: material
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          filters: []
          show_signature_annotations: true

nav:
  - 'index.md'
  - 'supported_datasets.md'
  - 'version_history.md'
  - 'code_of_conduct.md'
  - Joss Publication: 'joss_paper/pdr_joss_paper.pdf'
  - License: 'LICENSE.md'
  - API Reference: 'pdr_api.md'
