site_name: Planetary Data Reader
site_description: one tool to read them all; https://github.com/MillionConcepts/pdr
theme:
  name: readthedocs
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          filters: []

nav:
  - 'index.md'
  - 'supported_datasets.md'
  - 'version_history.md'
  - License: 'LICENSE.md'
  - API Reference: 'pdr_api.md'
