name: Binder Builder
on:
  push:
    branches:
    - main
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@ca0a6b7f0fdd7ffbe9d4cec0b9696f2dc658d3c9
      with:
        args: -O binder.html https://mybinder.org/v2/gh/millionconcepts/pdr/main
